/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMarketIntelligenceRouteImport } from './routes/_authenticated/market-intelligence'
import { Route as AuthenticatedFinancialHubRouteImport } from './routes/_authenticated/financial-hub'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDiseaseIdRouteImport } from './routes/_authenticated/disease-id'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTransportIndexRouteImport } from './routes/_authenticated/transport/index'
import { Route as AuthenticatedShopsIndexRouteImport } from './routes/_authenticated/shops/index'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace/index'
import { Route as AuthenticatedFarmersIndexRouteImport } from './routes/_authenticated/farmers/index'
import { Route as AuthenticatedTransportVehicleIdRouteImport } from './routes/_authenticated/transport/$vehicleId'
import { Route as AuthenticatedShopsShopIdRouteImport } from './routes/_authenticated/shops/$shopId'
import { Route as AuthenticatedMarketplaceListingIdRouteImport } from './routes/_authenticated/marketplace/$listingId'
import { Route as AuthenticatedFarmersFarmerIdRouteImport } from './routes/_authenticated/farmers/$farmerId'
import { Route as AuthenticatedCheckoutConfirmationRouteImport } from './routes/_authenticated/checkout.confirmation'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketIntelligenceRoute =
  AuthenticatedMarketIntelligenceRouteImport.update({
    id: '/market-intelligence',
    path: '/market-intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialHubRoute =
  AuthenticatedFinancialHubRouteImport.update({
    id: '/financial-hub',
    path: '/financial-hub',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiseaseIdRoute = AuthenticatedDiseaseIdRouteImport.update({
  id: '/disease-id',
  path: '/disease-id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransportIndexRoute =
  AuthenticatedTransportIndexRouteImport.update({
    id: '/transport/',
    path: '/transport/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShopsIndexRoute = AuthenticatedShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFarmersIndexRoute =
  AuthenticatedFarmersIndexRouteImport.update({
    id: '/farmers/',
    path: '/farmers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransportVehicleIdRoute =
  AuthenticatedTransportVehicleIdRouteImport.update({
    id: '/transport/$vehicleId',
    path: '/transport/$vehicleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShopsShopIdRoute =
  AuthenticatedShopsShopIdRouteImport.update({
    id: '/shops/$shopId',
    path: '/shops/$shopId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketplaceListingIdRoute =
  AuthenticatedMarketplaceListingIdRouteImport.update({
    id: '/marketplace/$listingId',
    path: '/marketplace/$listingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFarmersFarmerIdRoute =
  AuthenticatedFarmersFarmerIdRouteImport.update({
    id: '/farmers/$farmerId',
    path: '/farmers/$farmerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutConfirmationRoute =
  AuthenticatedCheckoutConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/community': typeof AuthenticatedCommunityRoute
  '/disease-id': typeof AuthenticatedDiseaseIdRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/financial-hub': typeof AuthenticatedFinancialHubRoute
  '/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/checkout/confirmation': typeof AuthenticatedCheckoutConfirmationRoute
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/marketplace/$listingId': typeof AuthenticatedMarketplaceListingIdRoute
  '/shops/$shopId': typeof AuthenticatedShopsShopIdRoute
  '/transport/$vehicleId': typeof AuthenticatedTransportVehicleIdRoute
  '/farmers/': typeof AuthenticatedFarmersIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/shops/': typeof AuthenticatedShopsIndexRoute
  '/transport/': typeof AuthenticatedTransportIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/community': typeof AuthenticatedCommunityRoute
  '/disease-id': typeof AuthenticatedDiseaseIdRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/financial-hub': typeof AuthenticatedFinancialHubRoute
  '/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/': typeof AuthenticatedIndexRoute
  '/checkout/confirmation': typeof AuthenticatedCheckoutConfirmationRoute
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/marketplace/$listingId': typeof AuthenticatedMarketplaceListingIdRoute
  '/shops/$shopId': typeof AuthenticatedShopsShopIdRoute
  '/transport/$vehicleId': typeof AuthenticatedTransportVehicleIdRoute
  '/farmers': typeof AuthenticatedFarmersIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/shops': typeof AuthenticatedShopsIndexRoute
  '/transport': typeof AuthenticatedTransportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/disease-id': typeof AuthenticatedDiseaseIdRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/financial-hub': typeof AuthenticatedFinancialHubRoute
  '/_authenticated/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/checkout/confirmation': typeof AuthenticatedCheckoutConfirmationRoute
  '/_authenticated/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/_authenticated/marketplace/$listingId': typeof AuthenticatedMarketplaceListingIdRoute
  '/_authenticated/shops/$shopId': typeof AuthenticatedShopsShopIdRoute
  '/_authenticated/transport/$vehicleId': typeof AuthenticatedTransportVehicleIdRoute
  '/_authenticated/farmers/': typeof AuthenticatedFarmersIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/shops/': typeof AuthenticatedShopsIndexRoute
  '/_authenticated/transport/': typeof AuthenticatedTransportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/disease-id'
    | '/equipment'
    | '/financial-hub'
    | '/market-intelligence'
    | '/checkout/confirmation'
    | '/farmers/$farmerId'
    | '/marketplace/$listingId'
    | '/shops/$shopId'
    | '/transport/$vehicleId'
    | '/farmers/'
    | '/marketplace/'
    | '/shops/'
    | '/transport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/disease-id'
    | '/equipment'
    | '/financial-hub'
    | '/market-intelligence'
    | '/'
    | '/checkout/confirmation'
    | '/farmers/$farmerId'
    | '/marketplace/$listingId'
    | '/shops/$shopId'
    | '/transport/$vehicleId'
    | '/farmers'
    | '/marketplace'
    | '/shops'
    | '/transport'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/checkout'
    | '/_authenticated/community'
    | '/_authenticated/disease-id'
    | '/_authenticated/equipment'
    | '/_authenticated/financial-hub'
    | '/_authenticated/market-intelligence'
    | '/_authenticated/'
    | '/_authenticated/checkout/confirmation'
    | '/_authenticated/farmers/$farmerId'
    | '/_authenticated/marketplace/$listingId'
    | '/_authenticated/shops/$shopId'
    | '/_authenticated/transport/$vehicleId'
    | '/_authenticated/farmers/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/shops/'
    | '/_authenticated/transport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market-intelligence': {
      id: '/_authenticated/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof AuthenticatedMarketIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial-hub': {
      id: '/_authenticated/financial-hub'
      path: '/financial-hub'
      fullPath: '/financial-hub'
      preLoaderRoute: typeof AuthenticatedFinancialHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disease-id': {
      id: '/_authenticated/disease-id'
      path: '/disease-id'
      fullPath: '/disease-id'
      preLoaderRoute: typeof AuthenticatedDiseaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transport/': {
      id: '/_authenticated/transport/'
      path: '/transport'
      fullPath: '/transport/'
      preLoaderRoute: typeof AuthenticatedTransportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shops/': {
      id: '/_authenticated/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof AuthenticatedShopsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers/': {
      id: '/_authenticated/farmers/'
      path: '/farmers'
      fullPath: '/farmers/'
      preLoaderRoute: typeof AuthenticatedFarmersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transport/$vehicleId': {
      id: '/_authenticated/transport/$vehicleId'
      path: '/transport/$vehicleId'
      fullPath: '/transport/$vehicleId'
      preLoaderRoute: typeof AuthenticatedTransportVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shops/$shopId': {
      id: '/_authenticated/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthenticatedShopsShopIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace/$listingId': {
      id: '/_authenticated/marketplace/$listingId'
      path: '/marketplace/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof AuthenticatedMarketplaceListingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers/$farmerId': {
      id: '/_authenticated/farmers/$farmerId'
      path: '/farmers/$farmerId'
      fullPath: '/farmers/$farmerId'
      preLoaderRoute: typeof AuthenticatedFarmersFarmerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/confirmation': {
      id: '/_authenticated/checkout/confirmation'
      path: '/confirmation'
      fullPath: '/checkout/confirmation'
      preLoaderRoute: typeof AuthenticatedCheckoutConfirmationRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
  }
}

interface AuthenticatedCheckoutRouteChildren {
  AuthenticatedCheckoutConfirmationRoute: typeof AuthenticatedCheckoutConfirmationRoute
}

const AuthenticatedCheckoutRouteChildren: AuthenticatedCheckoutRouteChildren = {
  AuthenticatedCheckoutConfirmationRoute:
    AuthenticatedCheckoutConfirmationRoute,
}

const AuthenticatedCheckoutRouteWithChildren =
  AuthenticatedCheckoutRoute._addFileChildren(
    AuthenticatedCheckoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDiseaseIdRoute: typeof AuthenticatedDiseaseIdRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedFinancialHubRoute: typeof AuthenticatedFinancialHubRoute
  AuthenticatedMarketIntelligenceRoute: typeof AuthenticatedMarketIntelligenceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFarmersFarmerIdRoute: typeof AuthenticatedFarmersFarmerIdRoute
  AuthenticatedMarketplaceListingIdRoute: typeof AuthenticatedMarketplaceListingIdRoute
  AuthenticatedShopsShopIdRoute: typeof AuthenticatedShopsShopIdRoute
  AuthenticatedTransportVehicleIdRoute: typeof AuthenticatedTransportVehicleIdRoute
  AuthenticatedFarmersIndexRoute: typeof AuthenticatedFarmersIndexRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedShopsIndexRoute: typeof AuthenticatedShopsIndexRoute
  AuthenticatedTransportIndexRoute: typeof AuthenticatedTransportIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDiseaseIdRoute: AuthenticatedDiseaseIdRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedFinancialHubRoute: AuthenticatedFinancialHubRoute,
  AuthenticatedMarketIntelligenceRoute: AuthenticatedMarketIntelligenceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFarmersFarmerIdRoute: AuthenticatedFarmersFarmerIdRoute,
  AuthenticatedMarketplaceListingIdRoute:
    AuthenticatedMarketplaceListingIdRoute,
  AuthenticatedShopsShopIdRoute: AuthenticatedShopsShopIdRoute,
  AuthenticatedTransportVehicleIdRoute: AuthenticatedTransportVehicleIdRoute,
  AuthenticatedFarmersIndexRoute: AuthenticatedFarmersIndexRoute,
  AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  AuthenticatedShopsIndexRoute: AuthenticatedShopsIndexRoute,
  AuthenticatedTransportIndexRoute: AuthenticatedTransportIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
